---
title: "Lab 4 - Deep Learning"
author: "Alex Vand"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: true
    code_folding: hide
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


# R

## Install python for R


```{r}
# load libraries
librarian::shelf(
  devtools,
  keras,
  reticulate,
  tensorflow)

# show library versions and paths
session_info() 

# install Python into user space
(reticulate::miniconda_path()) # show the Python path
if (!file.exists(reticulate::miniconda_path()))
  reticulate::install_miniconda()

# install keras with tensorflow
if (!keras::is_keras_available())
  keras::install_keras()
```


## Loading the MNIST dataset in Keras

```{r}
library(keras)
mnist <- dataset_mnist()
```


```{r}
train_images <- mnist$train$x
train_labels <- mnist$train$y
test_images  <- mnist$test$x
test_labels  <- mnist$test$y
```


```{r}
str(train_images)
```


```{r}
str(train_labels)
```


```{r}
str(test_images)
```


```{r}
str(test_labels)
```


```{r}
librarian::shelf(glue)

dim(train_images)
```

```{r}
dim(train_labels)
```

```{r}
par(mfrow=c(2,2))
sapply(
  1:4, function(i){ # i = 5
    plot(
      as.raster(train_images[i,,]/255),
      main = glue("image_{i}: label = {train_labels[i]}")) })
```




## The network architecture


```{r}
network <- keras_model_sequential() %>% 
  layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>% 
  layer_dense(units = 10, activation = "softmax")
```



## The compilation step

```{r}
network %>% compile(
  optimizer = "rmsprop",
  loss      = "categorical_crossentropy",
  metrics   = c("accuracy"))
```



## Preparing the image data

```{r}
train_images <- array_reshape(train_images, c(60000, 28 * 28))
train_images <- train_images / 255
test_images  <- array_reshape(test_images, c(10000, 28 * 28))
test_images  <- test_images / 255
```


## Preparing the labels

```{r}
train_labels <- to_categorical(train_labels)
test_labels  <- to_categorical(test_labels)
```


```{r}
network %>% fit(train_images, train_labels, epochs = 5, batch_size = 128)
```


```{r}
metrics <- network %>% evaluate(test_images, test_labels, verbose = 0)
metrics
```


# Python



# iNaturalist

```{r}
librarian::shelf(
  digest, dplyr, DT, glue, purrr, readr, stringr, tidyr)

# path to folder containing species directories of images
dir_train_mini <- "/courses/EDS232/inaturalist-2021/train_mini"

# get list of directories, one per species (n = 10,000 species)
dirs_spp <- list.dirs(dir_train_mini, recursive = F)
n_spp <- length(dirs_spp)
n_spp
```

```{r}
# set seed (for reproducible results) 
# just before sampling (otherwise get different results)
# based on your username (unique amongst class)
Sys.info()[["user"]] %>% 
  digest::digest2int() %>% 
  set.seed()
i10 <- sample(1:n_spp, 10)

# show the 10 indices sampled of the 10,000 possible 
i10
```


```{r}
# show the 10 species directory names
basename(dirs_spp)[i10]
```


```{r}
# show the first 2 species directory names
i2 <- i10[1:2]
basename(dirs_spp)[i2]
```

```{r}
# path to output table of paths, which could be read by R, eg readr::read_csv(), or Python, eg pandas.read_csv()
inat_spp_images_csv <- "~/inat_spp_images.csv"

d <- tibble(
  # get 10 species names
  species = basename(dirs_spp)[i10],
  # assign TRUE/FALSE for: 10 species (multi-class) and 2 species (binary)
  spp10 = TRUE,
  spp2  = c(T,T,rep(F,8)))
DT::datatable(d)
```



```{r}
d <- d %>% 
  mutate(
    # construct full path to species directory
    dir_species = file.path(dir_train_mini, species),
    tbl_images  = purrr::map(dir_species, function(dir){
      # create a tibble per species
      tibble(
        # list files in the species directory (n=50)
        image = list.files(dir),
        # assign subset per species
        subset = c(rep("train", 30), rep("validation", 10), rep("test", 10))) })) %>% 
  # go from a tibble with 10 species rows containing a nested tbl_images to unnested, ie 10 species * 50 images = 500 rows
  tidyr::unnest(tbl_images)

# write tibble to CSV file for subsequent reading
readr::write_csv(d, inat_spp_images_csv)

# show counts of image files per species and subset
d %>% 
  mutate(
    # truncate species to show one line per species
    species_trunc = stringr::str_trunc(species, 40)) %>% 
  select(species_trunc, subset) %>% 
  table()
```









